spring:
  application:
    name: notification-service

mail:
  host: smtp.gmail.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        starttls:
          enable: true
        auth: true


server:
  port: 8090