server:
  port: #Your port here, e.g. 8081

spring:
  cloud:
    gateway:
      default-filters:
        #- AddResponseHeader=X-Gateway-Service, EgorS-Gateway
      routes:
        #- id: security-service
        #  uri: http://localhost:8083
        #  predicates:
        #    - Path=/auth/login, /auth/register, /security-swagger/**
        #- id: test-route #test server which won't be used.
        #  uri: http://localhost:8080
        #  predicates:
        #    - Path=/test/**
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: #classpath:public-example.pem
