server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway-Service, EgorS-Gateway
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/login, /auth/register, /auth/kafka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem
