spring:
  application:
    name: security-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: # Url to your database
    driver-class-name: #driver class name, e.g. com.mysql.cj.jdbc.Driver
    username: # root
    password: # root

server:
  port: #8082